defaults:
  - _self_
  - environment@: ML

experiment:
  name: my_ML
  seed: 43

agent:
  name: my_agent
  agent_type: "Heuristic"
  actor:
    actor_type: "Heuristic"

data_pre_process:
  test_size: 0.25
  shuffle: True
  num_feature_columns: null
  num_label_columns: 6
  include_id: true


hydra:
  run:
    dir: logs/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${experiment.name}
    subdir: ${hydra.job.override_dirname}
